openapi: 3.0.3
info:
  title: Example Pet API
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
paths:
  /pets:
    get:
      operationId: listPets
      summary: List pets
      responses:
        '200':
          description: ok
